siteTitle="Reactjs.fr"
baseColor = "#e5bb31"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
  "/docs/some-additional-steps/",
]
